name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: icexpr
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker build -t icexpr/k8s-metrics-dashboard:$(jq -r '.version' package.json) .
    
    - name: Push the Docker image
      run: docker push icexpr/k8s-metrics-dashboard:$(jq -r '.version' package.json)
